name: Plan Terraform Configuration

# Run manually
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.6 # Specify your Terraform version here

      - name: Terraform Init and Plan
        run: |
          cd azure-vm
          terraform init
          terraform plan -input=false -var="admin_password=${{ secrets.VM_ADMIN_PASSWORD }}"
          env:
          TF_VAR_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}
